### ISSUE TITLE
How to include the transparency-grid.png?

### ISSUE THREAD

**Issue by webgeckos** [BraadMartin/components#12]
Hi,

thank you for the alpha-color-picker. It works fine. But for some reason I can't include the transparency-grid.png. The horizontal slider is missing. There is just the opacity number. I have all the files in the same folder and everything else is working fine. 

Do you know what could be the reason?

**Comment by BraadMartin** [comment]
Hello webgeckos,

Thanks for using my alpha color picker! The transparency-grid.png file is included [here](https://github.com/BraadMartin/components/blob/f5c6ca5c81b127a9c2a4e296b3a57d808845bfeb/customizer/alpha-color-picker/alpha-color-picker.css#L107) if you're using the Customizer control version of the alpha color picker and [here](https://github.com/BraadMartin/components/blob/f5c6ca5c81b127a9c2a4e296b3a57d808845bfeb/alpha-color-picker/alpha-color-picker.css#L97) if you're using the standalone version. Both are relative url css references. In most cases if you have the transparency-grid.png file in the same folder as the other files, as it is placed in this repo, it should work, but it's possible that in a symlink situation it might not show up correctly, or it's possible that due to server file permissions the file can't be loaded.

Can you inspect the css rules I linked to above in the CSS file that is loading on your site, and on the `background-image` property you should see where the transparency-grid.png file gets included and if you click on it you'll get the full URL your server is trying to find image at. If that URL isn't correct, all you need to do is change the URL in the css file in my code to match wherever the image is on your server. You'll know you have the right URL when you can enter the URL for the image into your browser and the image loads. If you know you have the right URL but still the image isn't loading, it's likely a file permissions issue.

If you don't see even the css and js files loading then it's likely that [this line](https://github.com/BraadMartin/components/blob/f5c6ca5c81b127a9c2a4e296b3a57d808845bfeb/customizer/alpha-color-picker/alpha-color-picker.php#L51) and the one below it that uses `get_stylesheet_directory_uri()` aren't resolving to the right path, possibly because you're using a child theme. To fix that try `get_template_directory_uri()` or similar until the css and js files start to load.

Let me know how it goes. I hope you get it working. Best of luck.

**Comment by webgeckos** [comment]
Thank you Braad for such a detailed response! I somehow managed it by including the jquery css file instead of wordpress customizer css file. Now its working!

I have now another question (let me know if I should open a new issue): For another project I used just the jquery version in one of my widgets. It works fine but when I click on one color the alpha color picker disappears and I see only the rgba value. After refreshing the page the color picker appears again.

And if I open up the theme customizer to edit the widgets I also see only the rgba value. There is no color picker. 

The selected color is always saved properly.

Do you have an idea what can cause this issue?

Thank you.
Daniel

**Comment by BraadMartin** [comment]
Because widgets are lazy loaded in the admin and in the Customizer, I think you'll have to hook into a JS event and reinitialize the color picker to get it working in these situations. I haven't tried to do this yet, but in theory it should work. Let me know how it goes 😉
