### ISSUE TITLE
Not replacing the color picker just adding a new field

### ISSUE THREAD

**Issue by ericatoyer** [BraadMartin/components#3]
I'm working with a child theme, I did not create the parent theme. I can only get the color picker to add a new field rather than replace the existing color pickers. Any ideas?

![screen shot 2015-07-29 at 5 42 11 pm](https://cloud.githubusercontent.com/assets/11182791/8970727/39e5cb5c-3619-11e5-9618-31c76f3fce53.png)

**Comment by BraadMartin** [comment]
Hmm, I see two issues. The first issue is that the Alpha Color Picker field you've added isn't matching the others (when closed, it should look exactly like the regular color picker triggers), which indicates that there is a JS error on the page. When you open up the Chrome dev tools, are there any JS errors showing in the console? If so, can you paste them here so I can see the errors?

The second issue is that the other color picker fields aren't automatically getting the alpha picker, and this is simply an issue of how the controls were registered. When you register each control using the Customizer API (i.e. $wp_customize->add_control) you have to specifically pass the control class you want to use. In the case of the Alpha Color Picker, you pass 'new Customize_Alpha_Color_Control', so the full control code might look something like this:

    $wp_customize->add_control(
		new Customize_Alpha_Color_Control(
			$wp_customize,
			'components_alpha_color_test_control',
			array(
				'label'     => __( 'Alpha Color Picker Test', 'components' ),
				'section'   => 'components_test_section',
				'settings'  => 'components_alpha_color_test_setting',
				'palette'   => array( '#006699', 'rgba( 20,20,20,0.7 )' ) 
			)
		)
	);

If the control wasn't registered using 'new Customize_Alpha_Color_Control', it won't use the Alpha Color Picker, and it sounds like the other color controls I see in your screenshot were registered using the standard 'new Customize_Color_Control', rather than 'new Customize_Alpha_Color_Control'.

If these controls were registered in a parent theme, you can still override them in your child theme to use the Alpha Color Picker. This involves doing your overrides on the 'customize_register' hook but at a later priority than what the parent theme is firing on. If you send me an example of the code you're using in your child theme along with the relevant code from the parent theme that registers the settings and controls, I can send you back what you'd need to make it work. Keep in mind that if you have a sanitize_callback registered on any of the color settings and the callback only allows valid hex color values to be saved, you might need to switch to a more permissive sanitize_callback so that the rgba values are saved correctly.

I hope this information helps. If you send me the JS errors you're seeing in the console and the code you're using to register the settings and controls in your child theme (and the parent theme if you want to also make the settings registered there use the Alpha Color Picker) I will dig in further and be able to give you more information to help get it working. :)

**Comment by BraadMartin** [comment]
@ericatoyer can you send me the information I mentioned in my previous reply? I'd love to get the Alpha Color Picker working for you.

**Comment by BraadMartin** [comment]
@ericatoyer since I haven't heard from you I'm going to close this issue, but please feel free to reopen it if there is still something I can help you with.
