### ISSUE TITLE
Not autorefresh of the page ?

### ISSUE THREAD

**Issue by batsteek** [BraadMartin/components#4]
Tested on 4.2 and 4.3RC2. I can customize colors on my theme but I can't get the page "live refresh" when I change the color value (just like with the standard color picker).

Am I doing something wrong ?

**Comment by BraadMartin** [comment]
Hello @batsteek,

When you define your color settings, you specify the 'transport' value as either 'postMessage' or 'refresh'. For example, this code registers a setting that uses 'postMessage':

````
// Alpha Color Picker Test Setting
$wp_customize->add_setting(
	'components_alpha_color_test_setting',
	array(
		'default'     => '#0099CC',
		'type'        => 'theme_mod',
		'capability'  => 'edit_theme_options',
		'transport'   => 'postMessage'
	)
);
````

Using postMessage used to be the only way to achieve true live previewing functionality, but it requires additional JS to make it work. You need to add some JS that does something like this:

````
( function( $ ) {

    wp.customize( 'components_alpha_color_test_setting', function( value ) {
    	value.bind( function( to ) {
        	$( 'body' ).css( 'background-color', to );
        } );
    } );

} )( jQuery );
````

This code says "When the user changes the color value using the Alpha Color Picker, grab the new color value and apply it as the background color on the main body element of the preview window". Without this extra JS, you won't get true live previews when using 'postMessage'.

*But wait!* The Customizer API is still being actively improved within WordPress core, and over the last couple of releases they have been trying to also improve the live previewing experience of settings registered using the 'refresh' transport method. In 4.2 and especially in 4.3, you'll notice that when you change settings registered using 'refresh' in the Customizer, the live preview fades out for a second and then fades back in with the updated setting value.

This fading in and out is sort of live previewing but technically the live preview window is just being refreshed with a transition fade. Eventually the goal is to only refresh the section of the page that was affected and you'll find lots of discussion on the Make Core blog and on Trac about the effort to achieve this under the name "Customizer Partial Refresh". There is even an [official feature plugin](https://wordpress.org/plugins/customize-partial-refresh/) that has been proposed for inclusion in WordPress 4.4 that adds this functionality right now.

So in order to achieve live previewing right now in 4.2 or 4.3, you need to either use transport 'postMessage' and include some extra JS to update the preview window when the user changes the color setting, or you need to use transport 'refresh' and accept that the page will fade out and back in with the new color. With either transport method, there is an assumption that you've set up your theme correctly to use the color value in your CSS, because the Alpha Color Picker control is just a mechanism for the user to pick a color, it knows nothing about how or where that color will be used.

I hope this information helps. I'm happy to take a look at the code you're using and suggest how you can get it working if you share it with me. Live previewing definitely works great using the Alpha Color Picker and I'm using it on several projects right now. Usually I prefer to use 'postMessage' and write my own JS to handle updating the preview when the user makes a change, but I'm watching the 'Customizer Partial Refresh' effort and looking forward to the further improvements that should come in 4.4.

**Comment by batsteek** [comment]
Hello Braad,

first, THANKS for taking the time to answer and for all the useful informations!
It's all ok now and I get the (Customizer Partial) Refresh transport running ok as well as my color settings are applied in the page styles.

As for the postMessage transport, it's the next step for my tests :)

Thanks for that, the alpha-color-picker is (imho ->really) missing in WP, at least for the Customizer and your code does the job!

**Comment by BraadMartin** [comment]
Glad to hear that you were able to get it working, and thank you for the kind words about the Alpha Color Picker. I certainly have had fun making it and am finding it very useful in my projects. I hope that one day an Alpha Color Picker does become a core field type, both in the Customizer and elsewhere throughout the wp-admin. The effort currently underway by @sc0ttclark for a [Fields API](https://github.com/sc0ttkclark/wordpress-fields-api) looks pretty awesome. Hopefully an Alpha Color Picker will be one of the Field types he includes.
