### ISSUE TITLE
Having trouble with "clear" button not triggering a refresh.

### ISSUE THREAD

**Issue by scofennell** [BraadMartin/components#7]
Hello Braad,

First, allow me to thank you for a really nice repo and also your community involvement.  I'm stoked about your work here.  Maybe at some point I can help with it!

For now though, I am having a slight issue and I'm not sure where to begin my debugging efforts. Please see the gif below:

http://www.gfycat.com/SmartLinedBorzoi

What I'm seeing is that clicking "clear" does not trigger an update.  The preview does not fade and the Save & Refresh button does not appear.  However, actually choosing a new color does trigger an update.  I want that behavior when I click "clear".

I am not getting any console errors.

Here's how I'm implementing your work:
https://gist.github.com/scofennell/0b088740bd07478dab12

And I'm passing the following args for add_control and add_setting:

```
array(3) {
  ["label"]=>
  string(15) "Body Text Color"
  ["section"]=>
  string(14) "globals-design"
  ["type"]=>
  string(11) "alpha-color"
}
array(3) {
  ["sanitize_callback"]=>
  string(19) "sanitize_text_field"
  ["sanitize_js_callback"]=>
  string(19) "sanitize_text_field"
  ["autoload"]=>
  bool(false)
}
```

I see a fair amount of discussion elsewhere in your repo on similar issues, but those tickets seem to pertain to live preview.  I'm not talking about live preview at all, I'm just talking about the page not updating at all, and my issue is specific to the "clear" button.

I'm going to try a reduced test case with a simpler theme, but in the meantime I'd love to hear any advice you have.

WP version: 4.4
Plugins: none
Theme: Don't even ask, it's huge and crazy
Browser: Chrome & FF Mac, likely others
Multisite install

**Comment by scofennell** [comment]
Breaking news.  In my control markup, I'm passing an empty string for data-default-color, since I don't want any particular color -- I literally want an empty string.  If I provide any color, the clear button works again.

Doesn't work:
```<input … data-default-color='' >```

Works:
```<input … data-default-color='rgba( 0, 0, 0, 0 )'> ```

That's kind of weird.  Fortunately, I'm finding that it works just as well if I totally omit the "data-default-color" attribute.  Good enough for me!

**Comment by BraadMartin** [comment]
Hello Scott,

Thank you for the thorough report and the kind words. You found a legitimate bug and I definitely wanted to fix, so I just did: https://github.com/BraadMartin/components/commit/7c87ad2616fea7b1563791831a8de410f244b045

This will properly set the option or theme_mod value to empty string if you click the Clear button, and it will pass this value to any live previewing JS that is hooked up. It's still up to your live preview JS to handle the empty string, so let's say you've got this:

```js
wp.customize( 'header_text_color', function( value ) {
	value.bind( function( to ) {
		$( '.site-header' ).css( 'color', to );
	});
});
```
You need to turn it into something like this:
```js
wp.customize( 'header_text_color', function( value ) {
	value.bind( function( to ) {
		if ( '' === to ) {
			$( '.site-header' ).css( 'color', 'rgba(0,0,0,0)' );
		} else {
			$( '.site-header' ).css( 'color', to );
		}
	});
});
```
This is necessary because if you just do `$( '.something' ).css( 'color', '' )`, you strip off the inline style declaration, but you don't override the value that may be coming from the stylesheet or an inline style element, and because the page hasn't refreshed since Clear was clicked, any original colors values will still be there. In the example above I handle this by specifically setting the preview color to transparent, which I think is a more accurate representation of empty color value.

I hope this helps you, and thank you for helping this repo!

-Braad
